title: <p align="center"> Mojdeh Hosseini </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/CV__DS.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mojdeh-haghighat-hosseini/">LinkedIn</a> |
  <a href="https://github.com/mojdeh-haghighat-hosseini">GitHub</a>
  </p>
  
  <p align="justify">
  I am a Data Scientist skilled in Python, SQL, PySpark, and Data Visualization. Passionate about AI & building data-driven solutions.
  <br><br>
  Holding a Master's degree in Computer Science from Concordia University, Montreal.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Replace with your own Google Analytics tracking ID
x
